/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const YouTubeVideo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'addedAt' : IDL.Int,
});
export const AddVideoResult = IDL.Variant({
  'ok' : YouTubeVideo,
  'err' : IDL.Text,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Certificate = IDL.Record({ 'id' : IDL.Nat, 'url' : IDL.Text });

export const idlService = IDL.Service({
  'addCertificate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text], [AddVideoResult], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'clearHeroPanelMedia' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getHeroPanelMedia' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
  'removeCertificate' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeYouTubeVideo' : IDL.Func([IDL.Nat], [], []),
  'setHeroPanelMedia' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const YouTubeVideo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'addedAt' : IDL.Int,
  });
  const AddVideoResult = IDL.Variant({ 'ok' : YouTubeVideo, 'err' : IDL.Text });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Certificate = IDL.Record({ 'id' : IDL.Nat, 'url' : IDL.Text });
  
  return IDL.Service({
    'addCertificate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addYouTubeVideo' : IDL.Func([IDL.Text, IDL.Text], [AddVideoResult], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'clearHeroPanelMedia' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getHeroPanelMedia' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getYouTubeVideos' : IDL.Func([], [IDL.Vec(YouTubeVideo)], ['query']),
    'removeCertificate' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeYouTubeVideo' : IDL.Func([IDL.Nat], [], []),
    'setHeroPanelMedia' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };