/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddVideoResult = { 'ok' : YouTubeVideo } |
  { 'err' : string };
export interface Certificate { 'id' : bigint, 'url' : string }
export type LoginResult = { 'ok' : string } |
  { 'err' : string };
export interface YouTubeVideo {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'addedAt' : bigint,
}
export interface _SERVICE {
  'addCertificate' : ActorMethod<[string, string], bigint>,
  'addYouTubeVideo' : ActorMethod<[string, string], AddVideoResult>,
  'adminLogin' : ActorMethod<[string, string], LoginResult>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'clearHeroPanelMedia' : ActorMethod<[string, bigint], undefined>,
  'getCertificates' : ActorMethod<[], Array<Certificate>>,
  'getHeroPanelMedia' : ActorMethod<[], Array<string>>,
  'getYouTubeVideos' : ActorMethod<[], Array<YouTubeVideo>>,
  'removeCertificate' : ActorMethod<[string, bigint], undefined>,
  'removeYouTubeVideo' : ActorMethod<[bigint], undefined>,
  'setHeroPanelMedia' : ActorMethod<[string, bigint, string], undefined>,
  'verifyAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];